"""create initial task tables

Revision ID: ca90a6bacce9
Revises: 
Create Date: 2026-06-11 18:57:50.423080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca90a6bacce9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complexity_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_duration', sa.String(length=100), nullable=True),
    sa.Column('coefficient', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_complexity_dict_id'), 'complexity_dict', ['id'], unique=False)
    op.create_table('priority_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('response_time', sa.String(length=100), nullable=True),
    sa.Column('coefficient', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_priority_dict_id'), 'priority_dict', ['id'], unique=False)
    op.create_table('task_score_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority_code', sa.String(length=50), nullable=False),
    sa.Column('complexity_code', sa.String(length=50), nullable=False),
    sa.Column('score_multiplier', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_score_matrix_id'), 'task_score_matrix', ['id'], unique=False)
    op.create_table('task_type_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_task_type_dict_id'), 'task_type_dict', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_title', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('task_type_id', sa.Integer(), nullable=True),
    sa.Column('business_area', sa.String(length=255), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('auto_status', sa.String(length=50), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.Column('complexity_id', sa.Integer(), nullable=True),
    sa.Column('auto_task_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('executor', sa.String(length=255), nullable=True),
    sa.Column('extra_column', sa.Text(), nullable=True),
    sa.Column('plan_fact', sa.Text(), nullable=True),
    sa.Column('fact_start_date', sa.Date(), nullable=True),
    sa.Column('planned_finish_date', sa.Date(), nullable=True),
    sa.Column('fact_finish_date', sa.Date(), nullable=True),
    sa.Column('fact_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('short_status_description', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complexity_id'], ['complexity_dict.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['priority_dict.id'], ),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_type_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_id'), 'task_events', ['id'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_table('task_previews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ai_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['target_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_previews_id'), 'task_previews', ['id'], unique=False)
    op.create_index(op.f('ix_task_previews_target_task_id'), 'task_previews', ['target_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_previews_target_task_id'), table_name='task_previews')
    op.drop_index(op.f('ix_task_previews_id'), table_name='task_previews')
    op.drop_table('task_previews')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_type_dict_id'), table_name='task_type_dict')
    op.drop_table('task_type_dict')
    op.drop_index(op.f('ix_task_score_matrix_id'), table_name='task_score_matrix')
    op.drop_table('task_score_matrix')
    op.drop_index(op.f('ix_priority_dict_id'), table_name='priority_dict')
    op.drop_table('priority_dict')
    op.drop_index(op.f('ix_complexity_dict_id'), table_name='complexity_dict')
    op.drop_table('complexity_dict')
    # ### end Alembic commands ###
